
spring.application.name=jpaTuts
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hiberate.format_sql = true

spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@Amr2603it

spring.application.name=Module1Demo
>>>>>>> dbb782f6c0ccad451b7edbe358acc769f1981990
